### ISSUE TITLE
Swap HTTP Library w/ Tesla

### ISSUE THREAD

**Issue by houllette** [hernanat/open_ai_ex#1]
Hey there! Thanks for all the hard work on this library!

I've been playing with it for a bit and looking through the codebase of this library as well as OpenAI's recommended best practices and realized that it may be prudent to implement some niceties to this library to allow for more scalability.

I see you mention in the README that you want to allow for HTTP adapter configurability, but I would actually recommend a slightly different approach - swap the HTTP library over to [Tesla](https://hexdocs.pm/tesla/readme.html) using the [Finch adapter](https://hexdocs.pm/tesla/Tesla.Adapter.Finch.html) by default (instead of using the Finch library directly). 

Using Tesla would open up the ability for the user of your library to choose a different adapter if need be, but also provides Tesla's excellent composability - one of the biggest benefits imo would be the addition of the [Retry middleware](https://hexdocs.pm/tesla/Tesla.Middleware.Retry.html) that we could wrap the network calls in since that is the [recommended path suggested by OpenAI](https://github.com/openai/openai-cookbook/blob/main/examples/How_to_handle_rate_limits.ipynb) for avoiding getting rate-limited.

**Comment by hernanat** [comment]
that's actually a really good point. Funny enough I pulled out some code from Tesla for multipart uploads anyways ... probably would have been simpler to just use it instead.

Would you like to take a stab at it? Otherwise I can try to get to it when I have some free time.

**Comment by houllette** [comment]
Happy to take a stab at it! Fair warning that I'm probably in a similar boat as yourself in that I will try to tackle it when I have some free time. Might have a free cycle or two to get a PR at least started here soon though!

**Comment by hernanat** [comment]
I started playing around with this a bit and the primary issue right now is that we are using the multipart library which conflicts with Tesla's own multipart implementation. When moving to Tesla I'd like to get rid of this library, but it will require us to do things like write our own implementation for computing the content length header since Tesla does not have this functionality out of the box (kind of disappointing but 🤷 )

**Comment by hernanat** [comment]
While were at ir w tesla im also thinking to make the json parser swappable. I think the flexibility will encourage more users to use the library and thus contribute

**Comment by hernanat** [comment]
wip in #6
