### ISSUE TITLE
JSON Native Support

### ISSUE THREAD

**Issue by houllette** [hernanat/open_ai_ex#2]
Coming out of Spawnfest 2022, [json_native](https://github.com/spawnfest/json_native) is an extension of :jason which adds a sprinkle of NIFs to make operations like Jason.encode! almost 1.5x faster for most inputs (and up to 8x faster than :jason for long strings).

It's very simple to adopt now as an optional dependency ({:jason_native, "\~> 0.1.0"}) in the mix.exs file, it just needs{:jason, "~> 1.5.0-alpha.1"}.

**Comment by hernanat** [comment]
closing and we can open up a PR when jason 1.5 is ready
